### ISSUE TITLE
Add scatterplot demos

### ISSUE THREAD

**Issue by thinkh** [ffg-seva/onboarding-prototype#40]
- [ ] Plotly https://plotly.com/javascript/line-and-scatter/
- [ ] Vega-Lite https://vega.github.io/vega-lite/examples/circle.html
- [ ] ECharts https://echarts.apache.org/examples/en/editor.html?c=scatter-simple

Apply cars dataset from Vega-Lite example for all demos.

**Comment by dg-datavisyn** [comment]
[accidents_2017.csv](https://github.com/ffg-seva/onboarding-prototype/files/6931327/accidents_2017.csv)
